### ISSUE TITLE
component_diagram

### ISSUE THREAD

**Issue by AniSkyWorker** [venera13/go#1]
- [x] Хорошо бы добавить описание или отразить, каким образом добавление рецензий будет влиять на фильм. Просто как список? Важно ли почему-то синхронизировать данные? Я же могу получить список рецензий и в самом сервисе рецензий

**Comment by venera13** [comment]
Поменяла диаграмм - добавила "Рейтинг фильма". При оценке фильма нужно будет получить текущий рейтинг фильма и переоценить его. Подробнее - в диаграмме последовательностей
