### ISSUE TITLE
sequence_diagram

### ISSUE THREAD

**Issue by AniSkyWorker** [venera13/go#2]
- [x] Не понятно, а зачем синхронно добавлять к фильму отзыв? Можно же связку фильм-отзыв хранить в самом сервисе рецензий. Нужна операция посложнее, сейчас получается, что сервисы могут быть независимы друг от друга, не хватает какой-то хитрой логики) мб рейтинг фильма или что-то такое

**Comment by venera13** [comment]
Добавила операцию оценки фильма, остальные диаграммы тоже поменяла

**Comment by AniSkyWorker** [comment]
- [x] Я имел ввиду, что нужна какая-то межсервисная синхронизация или зависимая логика.
Сейчас получилось следующее, у нас есть рейтинг фильма, но он зачем-то ходит к фильму, чтобы узнать его рейтинг и перезаписать его.
Т.е. сам сервис рейтинга каким-то состоянием не обладает, а просто умеет считать рейтинг. Он вполне мог бы сам хранить рейтинг фильма(для этого в api нужно всего лишь передавать id фильма) и тогда не нужно делать запросы в сервис фильмов.

Для примера, как должно быть: 
1) рецензию или рейтинг можно поставить фильму, только если он уже вышел в прокат. Cервису рейтинга действительно придётся дернуть сервис фильмов, чтобы узнать вышел ли уже фильм и вообще существует ли фильм с id, который передали в сервис рейтингов. Т.к. он хоть и хранит рейтинг фильма, но информацией о фильме не обладает.
2) при удалении фильма - стираются все рецензии. Теперь сервис рецензий обязан отслеживать событие удаления фильма. И по id удалять рецензии

Предлагаю расписать пару вот таких сложных операций и оставить какой-то один компонент для начала - или рейтинг, или рецензии

**Comment by AniSkyWorker** [comment]
Можно вполне обновлять диаграммы через гит, чтобы не создавать новые файлы. Всё равно сможем восстановить предыдущую через историю коммитов

**Comment by venera13** [comment]
Добавила диаграммы:
1. для приведенных примеров
2. для кейса просмотра списка рекомендуемых фильмов - топ по рейтингу.
